# Generated by Django 2.0.1 on 2018-02-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=10000, unique=True)),
                ('option_a', models.CharField(max_length=1000)),
                ('option_b', models.CharField(max_length=1000)),
                ('option_c', models.CharField(max_length=1000)),
                ('option_d', models.CharField(max_length=1000)),
                ('solution', models.IntegerField()),
            ],
        ),
    ]
